### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by scratties** [Drag0nDev/Stella#8]
When I start the bot I get an error like this:

![image](https://user-images.githubusercontent.com/73654370/114273314-3a24fc00-9a22-11eb-80ac-0f678244260c.png)

**Comment by Drag0nDev** [comment]
you still need to create the database

**Comment by scratties** [comment]
How can I create it? Can you tell

**Comment by Drag0nDev** [comment]
just run `node db` and it should be created

**Comment by scratties** [comment]
I am getting an error like this:

![image](https://user-images.githubusercontent.com/73654370/114273912-c7695000-9a24-11eb-928e-094bd4181968.png)

**Comment by Drag0nDev** [comment]
just checked it myself since it is a long time ago that I had to do it 
The command should be `node Hinata.Core/misc/loadDb.js`
This has to be done from the folder the bot is in

**Comment by scratties** [comment]
Thanks bro, got it. Thanks for your help.
